"""changed reference_id to string

Revision ID: 03c27c469bef
Revises: 49c5d6bccddb
Create Date: 2022-02-15 23:41:36.518413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c27c469bef'
down_revision = '49c5d6bccddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('reference_id', sa.String(), nullable=False))
    op.drop_constraint('deposit_reference_key', 'deposit', type_='unique')
    op.create_unique_constraint(None, 'deposit', ['reference_id'])
    op.drop_column('deposit', 'reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('reference', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deposit', type_='unique')
    op.create_unique_constraint('deposit_reference_key', 'deposit', ['reference'])
    op.drop_column('deposit', 'reference_id')
    # ### end Alembic commands ###
