"""changed email to accept null

Revision ID: 3b475dbc0c53
Revises: ea7e4715659b
Create Date: 2022-02-03 01:37:00.415491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b475dbc0c53'
down_revision = 'ea7e4715659b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refered_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refered_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'refered_id')
    )
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('referals')
    # ### end Alembic commands ###
