"""make reference_id unique

Revision ID: 48f0dd8e49e8
Revises: 99e1492f1573
Create Date: 2022-02-15 20:53:30.081479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f0dd8e49e8'
down_revision = '99e1492f1573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'deposit', ['reference_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deposit', type_='unique')
    # ### end Alembic commands ###
