"""changed some columns

Revision ID: 615a88edfe42
Revises: 9459309f0892
Create Date: 2022-01-26 16:54:17.748393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615a88edfe42'
down_revision = '9459309f0892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_branches', 'longitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('merchant_branches', 'lattitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_branches', 'lattitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('merchant_branches', 'longitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
