"""add admin table

Revision ID: 904b5e009747
Revises: 898ef5ffe0c9
Create Date: 2022-01-20 23:45:08.189946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '904b5e009747'
down_revision = '898ef5ffe0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column("status", postgresql.ENUM("active", "disabled", "pending", name='status', create_type=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )

    admin = table("admin", 
    column("name", sa.String()), 
    column("username", sa.String()), 
    column("password", sa.String()), 
    column("status", sa.Enum()),
    )

    op.bulk_insert(admin, 
    [
        {
            'name': 'Tommy', 
            'username': 'root',
            'password': '$2b$12$eD6QDhR51DMG.x6EQrzAt.vVTqx2FITdR3RlEYQK11bq/u3.vCVKS',
            'status': 'active'
        }
    ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
