"""add country and state column to MerchantBranch

Revision ID: 9459309f0892
Revises: e61c9699c6ac
Create Date: 2022-01-24 17:03:48.749744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9459309f0892'
down_revision = 'e61c9699c6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_branches', sa.Column('country', sa.Integer(), nullable=True))
    op.add_column('merchant_branches', sa.Column('state', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'merchant_branches', 'countries', ['country'], ['id'])
    op.create_foreign_key(None, 'merchant_branches', 'states', ['state'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchant_branches', type_='foreignkey')
    op.drop_constraint(None, 'merchant_branches', type_='foreignkey')
    op.drop_column('merchant_branches', 'state')
    op.drop_column('merchant_branches', 'country')
    # ### end Alembic commands ###
