"""remove foreign key from merchant branch on merchant staff table

Revision ID: e61c9699c6ac
Revises: 904b5e009747
Create Date: 2022-01-21 01:36:29.478936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61c9699c6ac'
down_revision = '904b5e009747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_staff', 'merchant_branch',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('merchant_staff_merchant_branch_fkey', 'merchant_staff', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('merchant_staff_merchant_branch_fkey', 'merchant_staff', 'merchant_branches', ['merchant_branch'], ['id'], ondelete='CASCADE')
    op.alter_column('merchant_staff', 'merchant_branch',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
